
[project]
description = "wallet secret and env var tool"
authors = [ { name = "Mr. Mattie" , email = "mattie@codermattie.net" } ]

homepage = "https://github.com/bitcathedrals/utilities/"
repository = "https://github.com/bitcathedrals/utilities.git"

[scripts]
wallet = "wallet.wallet:exec"
