
[project]
description = "wallet secret and env var tool"
authors = [ { name = "Michael Mattie" , email = "codermattie@runbox.com" } ]

homepage = "https://github.com/bitcathedrals/utilities/"
repository = "https://github.com/bitcathedrals/utilities.git"

[scripts]
wallet = "wallet.wallet:exec"
